name: lc0-nvidia # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.26.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: The Leela Chess Zero chess engine # 79 char long summary
description: |
  This is a test build of the Leela Chess Zero chess engine.
  https://github.com/LeelaChessZero/lc0/

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64
  # - build-on: i386
  #   run-on: i386

apps:
  lc0:
    command: bin/lc0-cuda91
    plugs:
      - home
  lc0-blas:
    command: bin/lc0-blas
    plugs:
      - home

parts:
  cuda91:
    plugin: meson
    meson-parameters:
      - -Dbuildtype=release
      - -Dgtest=false
      - -Dblas=false
      - -Dopencl=false
    build-packages:
      - gcc-8
      - g++-8
      - libstdc++-8-dev
      - nvidia-cuda-toolkit
    stage-packages:
      - libcudart9.1
      - libcublas9.1
    build-environment:
      - CC: "gcc-8"
      - CXX: "g++-8"
    override-build: |
      pip3 install --upgrade meson==0.55.3
      snapcraftctl build
      mv $SNAPCRAFT_PART_INSTALL/usr/local/bin/lc0 $SNAPCRAFT_PART_INSTALL/usr/local/bin/lc0-cuda91
    source: https://github.com/LeelaChessZero/lc0.git
    source-type: git
    source-depth: 1
    source-tag: 'v0.26.3'

  blas:
    plugin: meson
    meson-parameters:
      - -Dbuildtype=release
      - -Dgtest=false
      - -Dopencl=false
    build-packages:
      - gcc-8
      - g++-8
      - libstdc++-8-dev
    build-environment:
      - CC: "gcc-8"
      - CXX: "g++-8"
    override-build: |
      pip3 install --upgrade meson==0.55.3
      snapcraftctl build
      mv $SNAPCRAFT_PART_INSTALL/usr/local/bin/lc0 $SNAPCRAFT_PART_INSTALL/usr/local/bin/lc0-blas
    source: https://github.com/LeelaChessZero/lc0.git
    source-type: git
    source-depth: 1
    source-tag: 'v0.26.3'
